In [2]:
import pandas as pd
import sqlite3
from pathlib import Path

In [3]:
project_folder = Path.cwd().parent

csv_path = project_folder / "data" / "train.csv"
database_path = project_folder / "data" / "retail_sales.db"

print("CSV:", csv_path)
print("Database:", database_path)

CSV: c:\Users\4155a\OneDrive\Documents\Data-Analytics-Portfolio\Retail-Sales-Performance-Dashboard\data\train.csv
Database: c:\Users\4155a\OneDrive\Documents\Data-Analytics-Portfolio\Retail-Sales-Performance-Dashboard\data\retail_sales.db

In [4]:
df = pd.read_csv(csv_path)

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [5]:
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
      .str.replace("-", "_")
)

df.columns.tolist()

['row_id',
 'order_id',
 'order_date',
 'ship_date',
 'ship_mode',
 'customer_id',
 'customer_name',
 'segment',
 'country',
 'city',
 'state',
 'postal_code',
 'region',
 'product_id',
 'category',
 'sub_category',
 'product_name',
 'sales']

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   row_id         9800 non-null   int64
 1   order_id       9800 non-null   str
 2   order_date     9800 non-null   str
 3   ship_date      9800 non-null   str
 4   ship_mode      9800 non-null   str
 5   customer_id    9800 non-null   str
 6   customer_name  9800 non-null   str
 7   segment        9800 non-null   str
 8   country        9800 non-null   str
 9   city           9800 non-null   str
 10  state          9800 non-null   str
 11  postal_code    9789 non-null   float64
 12  region         9800 non-null   str
 13  product_id     9800 non-null   str
 14  category       9800 non-null   str
 15  sub_category   9800 non-null   str
 16  product_name   9800 non-null   str
 17  sales          9800 non-null   float64
dtypes: float64(2), int64(1), str(15)
memory usage: 1.3 MB

In [7]:
df["order_date"] = pd.to_datetime(df["order_date"], dayfirst=True)
df["ship_date"] = pd.to_datetime(df["ship_date"], dayfirst=True)

df[["order_date", "ship_date"]].head()

  order_date  ship_date
0 2017-11-08 2017-11-11
1 2017-11-08 2017-11-11
2 2017-06-12 2017-06-16
3 2016-10-11 2016-10-18
4 2016-10-11 2016-10-18

In [8]:
df["postal_code"] = df["postal_code"].astype("Int64")

df[["postal_code"]].head()

   postal_code
0        42420
1        42420
2        90036
3        33311
4        33311

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   row_id         9800 non-null   int64
 1   order_id       9800 non-null   str
 2   order_date     9800 non-null   datetime64[us]
 3   ship_date      9800 non-null   datetime64[us]
 4   ship_mode      9800 non-null   str
 5   customer_id    9800 non-null   str
 6   customer_name  9800 non-null   str
 7   segment        9800 non-null   str
 8   country        9800 non-null   str
 9   city           9800 non-null   str
 10  state          9800 non-null   str
 11  postal_code    9789 non-null   Int64
 12  region         9800 non-null   str
 13  product_id     9800 non-null   str
 14  category       9800 non-null   str
 15  sub_category   9800 non-null   str
 16  product_name   9800 non-null   str
 17  sales          9800 non-null   float64
dtypes: Int64(1), datetime64[us](2), float64(1), int64(1), str(13)
memory usage: 1.4 MB

In [10]:
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,state,postal_code,region,product_id,category,sub_category,product_name,sales
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [11]:
connection = sqlite3.connect(database_path)

print("Connected to SQLite database.")

Connected to SQLite database.

In [12]:
df.to_sql(
    name="retail_sales",
    con=connection,
    if_exists="replace",
    index=False
)

print("Data loaded into the retail_sales table.")

Data loaded into the retail_sales table.

In [20]:
tables_query = """
SELECT name
FROM sqlite_master
WHERE type = 'table';
"""

pd.read_sql_query(tables_query, connection)

           name
0  retail_sales

In [18]:
preview_query = """
SELECT *
FROM retail_sales
LIMIT 5;
"""

pd.read_sql_query(preview_query, connection)

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,state,postal_code,region,product_id,category,sub_category,product_name,sales
0,1,CA-2017-152156,2017-11-08 00:00:00,2017-11-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,2017-11-08 00:00:00,2017-11-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,2017-06-12 00:00:00,2017-06-16 00:00:00,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,2016-10-11 00:00:00,2016-10-18 00:00:00,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,2016-10-11 00:00:00,2016-10-18 00:00:00,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [23]:
row_count_query = """
SELECT COUNT(*) AS total_rows
FROM retail_sales;
"""

pd.read_sql_query(row_count_query, connection)

   total_rows
0        9800

In [24]:
schema_query = """ 
PRAGMA table_info(retail_sales);
"""

pd.read_sql_query(schema_query, connection)

    cid           name       type  notnull dflt_value  pk
0     0         row_id    INTEGER        0       None   0
1     1       order_id       TEXT        0       None   0
2     2     order_date  TIMESTAMP        0       None   0
3     3      ship_date  TIMESTAMP        0       None   0
4     4      ship_mode       TEXT        0       None   0
5     5    customer_id       TEXT        0       None   0
6     6  customer_name       TEXT        0       None   0
7     7        segment       TEXT        0       None   0
8     8        country       TEXT        0       None   0
9     9           city       TEXT        0       None   0
10   10          state       TEXT        0       None   0
11   11    postal_code    INTEGER        0       None   0
12   12         region       TEXT        0       None   0
13   13     product_id       TEXT        0       None   0
14   14       category       TEXT        0       None   0
15   15   sub_category       TEXT        0       None   0
16   16   product_name       TEXT        0       None   0
17   17          sales       REAL        0       None   0

In [35]:
query = """ 
SELECT 
    ROUND(SUM(sales), 2) AS total_sales
FROM retail_sales;
"""

pd.read_sql_query(query, connection)

   total_sales
0   2261536.78

In [40]:
category = """ 
SELECT
    category,          
    ROUND(SUM(sales), 2) AS total_category_sales         
FROM retail_sales
GROUP BY
    category
ORDER BY
    total_category_sales desc;
""" 

pd.read_sql_query(category, connection)

          category  total_category_sales
0       Technology             827455.87
1        Furniture             728658.58
2  Office Supplies             705422.33

In [45]:
product = """ 
SELECT

    product_name,

    ROUND(SUM(sales), 2) AS total_product_sales

FROM retail_sales

GROUP BY

    product_name

ORDER BY

    total_product_sales DESC
LIMIT 10;
"""

pd.read_sql_query(product, connection)

                                        product_name  total_product_sales
0              Canon imageCLASS 2200 Advanced Copier             61599.82
1  Fellowes PB500 Electric Punch Plastic Comb Bin...             27453.38
2  Cisco TelePresence System EX90 Videoconferenci...             22638.48
3       HON 5400 Series Task Chairs for Big and Tall             21870.58
4         GBC DocuBind TL300 Electric Binding System             19823.48
5   GBC Ibimaster 500 Manual ProClick Binding System             19024.50
6               Hewlett Packard LaserJet 3310 Copier             18839.69
7  HP Designjet T520 Inkjet Large Format Printer ...             18374.90
8          GBC DocuBind P400 Electric Binding System             17965.07
9        High Speed Automatic Electric Letter Opener             17030.31

In [46]:
region = """ 
SELECT
    ROUND(SUM(sales), 2) AS western_sales
FROM retail_sales
WHERE
    region = 'West';
"""

pd.read_sql_query(region, connection)

   western_sales
0      710219.68

In [47]:
region = """ 
SELECT
    category,
    ROUND(SUM(sales), 2) AS western_sales
FROM retail_sales
WHERE
    region = 'West'
GROUP BY
    category
ORDER BY
    western_sales DESC;
"""

pd.read_sql_query(region, connection)

          category  western_sales
0       Technology      247404.93
1        Furniture      245348.25
2  Office Supplies      217466.51

In [48]:
west_customers = """ 
SELECT
    customer_name,
    ROUND(SUM(sales), 2) AS west_customers
FROM retail_sales
WHERE
    region = 'West'
GROUP BY
    customer_name
ORDER BY
    west_customers DESC
LIMIT 10;
"""

pd.read_sql_query(west_customers, connection)

    customer_name  west_customers
0    Raymond Buch        14345.28
1    Ken Lonsdale         8472.39
2    Edward Hooks         7408.09
3       Jane Waco         7391.53
4  Karen Ferguson         7182.77
5   Nick Crebassa         6734.23
6     Clay Ludtke         6069.64
7   Yana Sorensen         5754.17
8      Nora Preis         5564.60
9   William Brown         5523.05

In [49]:
orders = """ 
SELECT
    region,
    COUNT(order_id) AS total_orders
FROM retail_sales
GROUP BY
    region
ORDER BY
    total_orders DESC;
"""

pd.read_sql_query(orders,connection)

    region  total_orders
0     West          3140
1     East          2785
2  Central          2277
3    South          1598

In [50]:
customer_orders = """ 
SELECT
    customer_name,
    COUNT(order_id) AS total_orders
FROM retail_sales
GROUP BY
    customer_name
ORDER BY
    total_orders DESC
LIMIT 10;
"""

pd.read_sql_query(customer_orders, connection)

         customer_name  total_orders
0        William Brown            35
1           Paul Prost            34
2         Matt Abelman            34
3             John Lee            33
4          Seth Vernon            32
5     Jonathan Doherty            32
6  Chloris Kastensmidt            32
7     Zuschuss Carroll            31
8           Emily Phan            31
9       Arthur Prichep            31

In [52]:
average_sales = """ 
SELECT
    category,
    ROUND(AVG(sales), 2) AS average_sales
FROM retail_sales
GROUP BY category
ORDER BY average_sales DESC;
"""

pd.read_sql_query(average_sales, connection)

          category  average_sales
0       Technology         456.40
1        Furniture         350.65
2  Office Supplies         119.38

In [57]:
total_sales = """ 
SELECT
    category,
    ROUND(SUM(sales), 2) AS total_sales
FROM retail_sales
GROUP BY category
HAVING SUM(sales) > 700000
ORDER BY total_sales DESC;
"""

pd.read_sql_query(total_sales,connection)

          category  total_sales
0       Technology    827455.87
1        Furniture    728658.58
2  Office Supplies    705422.33

In [61]:
max_min_sales = """ 
SELECT
    category,
    ROUND(MAX(sales), 2) AS highest_sale,
    ROUND(MIN(sales), 2) AS lowest_sale
FROM retail_sales
GROUP BY category
ORDER BY highest_sale DESC;
"""

pd.read_sql_query(max_min_sales,connection)

          category  highest_sale  lowest_sale
0       Technology      22638.48         0.99
1  Office Supplies       9892.74         0.44
2        Furniture       4416.17         1.89

In [62]:
technology_sales = """ 
SELECT
    category,
    ROUND(sales, 2) AS sales
FROM retail_sales
WHERE region = 'West'
  AND category = 'Technology'
  AND sales > 500
ORDER BY sales DESC
LIMIT 10;
"""

pd.read_sql_query(technology_sales,connection)

     category     sales
0  Technology  13999.96
1  Technology   4799.98
2  Technology   4476.80
3  Technology   4158.91
4  Technology   3359.95
5  Technology   3357.60
6  Technology   3347.37
7  Technology   3149.93
8  Technology   3023.93
9  Technology   2999.95

In [65]:
region_sales = """ 
SELECT
    region,
    category,
    ROUND(sales, 2) AS sales
FROM retail_sales
WHERE
    (region = 'East' OR region = 'West')
    AND sales > 1000
ORDER BY sales DESC
LIMIT 10;
"""

pd.read_sql_query(region_sales,connection)

  region         category     sales
0   West       Technology  13999.96
1   East       Technology  11199.97
2   East       Technology  10499.97
3   East       Technology   9099.93
4   East       Technology   8399.98
5   West  Office Supplies   8187.65
6   East       Technology   6999.96
7   East       Technology   5399.91
8   East       Technology   5199.96
9   West  Office Supplies   5083.96

In [66]:
chair_sales = """ 
SELECT
    product_name,
    category,
    ROUND(sales, 2) AS sales
FROM retail_sales
WHERE product_name LIKE '%Chair%'
ORDER BY sales DESC
LIMIT 10;
"""

pd.read_sql_query(chair_sales,connection)

                                        product_name   category    sales
0       HON 5400 Series Task Chairs for Big and Tall  Furniture  4416.17
1       HON 5400 Series Task Chairs for Big and Tall  Furniture  3785.29
2       HON 5400 Series Task Chairs for Big and Tall  Furniture  3504.90
3  Hon 4070 Series Pagoda Armless Upholstered Sta...  Furniture  2888.13
4  Office Star - Professional Matrix Back Chair w...  Furniture  2807.84
5       HON 5400 Series Task Chairs for Big and Tall  Furniture  2803.92
6       HON 5400 Series Task Chairs for Big and Tall  Furniture  2803.92
7         GuestStacker Chair with Chrome Finish Legs  Furniture  2676.67
8                           Hon Olson Stacker Chairs  Furniture  2621.32
9            Global Deluxe High-Back Manager's Chair  Furniture  2573.82

In [67]:
furniture_technology_sales = """ 
SELECT
    product_name,
    category,
    ROUND(sales, 2) AS sales
FROM retail_sales
WHERE category IN ('Furniture', 'Technology')
  AND sales > 500
ORDER BY sales DESC
LIMIT 10;
"""

pd.read_sql_query(furniture_technology_sales,connection)

                                        product_name    category     sales
0  Cisco TelePresence System EX90 Videoconferenci...  Technology  22638.48
1              Canon imageCLASS 2200 Advanced Copier  Technology  17499.95
2              Canon imageCLASS 2200 Advanced Copier  Technology  13999.96
3              Canon imageCLASS 2200 Advanced Copier  Technology  11199.97
4              Canon imageCLASS 2200 Advanced Copier  Technology  10499.97
5   3D Systems Cube Printer, 2nd Generation, Magenta  Technology   9099.93
6  HP Designjet T520 Inkjet Large Format Printer ...  Technology   8749.95
7              Canon imageCLASS 2200 Advanced Copier  Technology   8399.98
8          Lexmark MX611dhe Monochrome Laser Printer  Technology   8159.95
9          Cubify CubeX 3D Printer Triple Head Print  Technology   7999.98

In [ ]:
between_sales = """ 
SELECT
    order_id,
    product_name,
    ROUND(sales, 2) AS sales
FROM retail_sales
WHERE sales BETWEEN 500 AND 1000
ORDER BY sales DESC
LIMIT 10;
"""

pd.read_sql_query(between_sales,connection)

         order_id                                       product_name   sales
0  CA-2016-156104  Hewlett Packard 610 Color Digital Copier / Pri...  999.98
1  CA-2017-166429  Hewlett Packard 610 Color Digital Copier / Pri...  999.98
2  CA-2016-135685                      Logitech diNovo Edge Keyboard  999.96
3  CA-2016-146563                     Hot File 7-Pocket, Floor Stand  999.43
4  CA-2015-121629    StarTech.com 10/100 VDSL2 Ethernet Extender Kit  998.85
5  CA-2015-159520  Chromcraft Bull-Nose Wood 48" x 96" Rectangula...  991.76
6  CA-2016-140984                             Economy Rollaway Files  991.20
7  CA-2016-158491  Logitech Z-906 Speaker sys - home theater - 5....  989.97
8  CA-2015-143903       HON 5400 Series Task Chairs for Big and Tall  981.37
9  CA-2017-168753                               Panasonic KX-TG9471B  979.95

In [71]:
case_when = """ 
SELECT
    product_name,
    ROUND(sales, 2) AS sales,
    CASE
        WHEN sales < 100 THEN 'Low'
        WHEN sales BETWEEN 100 AND 500 THEN 'Medium'
        ELSE 'High'
    END AS sales_category
FROM retail_sales
LIMIT 10;
"""

pd.read_sql_query(case_when,connection)

                                        product_name   sales sales_category
0                  Bush Somerset Collection Bookcase  261.96         Medium
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.94           High
2  Self-Adhesive Address Labels for Typewriters b...   14.62            Low
3      Bretford CR4500 Series Slim Rectangular Table  957.58           High
4                     Eldon Fold 'N Roll Cart System   22.37            Low
5  Eldon Expressions Wood and Plastic Desk Access...   48.86            Low
6                                         Newell 322    7.28            Low
7                     Mitel 5320 IP Phone VoIP phone  907.15           High
8  DXL Angle-View Binders with Locking Rings by S...   18.50            Low
9                   Belkin F5C206VTEL 6 Outlet Surge  114.90         Medium